#!/bin/bash

cd ~/Desktop/LAB || exit

git add .

if git diff --cached --quiet; then
    echo "Nothing to commit"
else
    DATE=$(date '+%Y-%m-%d %H:%M:%S')
    git commit -m "auto update $DATE"
fi

git pull origin main --rebase

git push origin main

echo "LAB synced 🚀"
